# Generated by Django 5.1.6 on 2025-04-07 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=40)),
                ('book_author', models.CharField(blank=True, max_length=40, null=True)),
                ('book_desc', models.TextField(blank=True, null=True)),
                ('book_price', models.IntegerField(blank=True, null=True)),
                ('book_image', models.ImageField(blank=True, null=True, upload_to='book_images')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_genre', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.book')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='book_genre',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.genre'),
        ),
        migrations.CreateModel(
            name='NewArrival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=40, null=True)),
                ('book_desc', models.TextField(blank=True, null=True)),
                ('book_author', models.CharField(blank=True, max_length=40, null=True)),
                ('book_price', models.IntegerField(blank=True, null=True)),
                ('book_image', models.ImageField(blank=True, null=True, upload_to='book_images')),
                ('arrival_date', models.DateTimeField(auto_now_add=True)),
                ('book_genre', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Trending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=40, null=True)),
                ('book_desc', models.TextField(blank=True, null=True)),
                ('book_price', models.IntegerField(blank=True, null=True)),
                ('book_image', models.ImageField(blank=True, null=True, upload_to='book_images')),
                ('arrival_date', models.DateTimeField(auto_now_add=True)),
                ('book_author', models.CharField(blank=True, max_length=40, null=True)),
                ('book_genre', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.genre')),
            ],
        ),
    ]
