# Generated by Django 5.1.6 on 2025-02-28 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
