# Generated by Django 5.1.6 on 2025-04-15 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitem',
            name='book_author',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
