# Generated by Django 5.1.6 on 2025-04-02 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='user',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='user',
        ),
        migrations.RemoveField(
            model_name='newarrival',
            name='user',
        ),
        migrations.RemoveField(
            model_name='trending',
            name='user',
        ),
    ]
