# Generated by Django 5.1.6 on 2025-04-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_remove_book_user_remove_contact_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_author',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='newarrival',
            name='book_author',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='trending',
            name='book_author',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
