# Generated by Django 5.1.6 on 2025-03-11 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_newarrival'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newarrival',
            name='book',
        ),
        migrations.AddField(
            model_name='newarrival',
            name='book_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newarrival',
            name='book_genre',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.genre'),
        ),
        migrations.AddField(
            model_name='newarrival',
            name='book_image',
            field=models.ImageField(blank=True, null=True, upload_to='book_images'),
        ),
        migrations.AddField(
            model_name='newarrival',
            name='book_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='newarrival',
            name='book_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newarrival',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
