# Generated by Django 5.1.6 on 2025-03-16 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_remove_newarrival_book_newarrival_book_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_author',
            field=models.TextField(blank=True, null=True),
        ),
    ]
