# Generated by Django 5.1.6 on 2025-04-22 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
