# Generated by Django 5.1.6 on 2025-03-23 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_alter_cart_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='price',
        ),
    ]
