# Generated by Django 5.1.6 on 2025-04-23 17:52

import API.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_remove_payment_user_comment_rating_delete_bookorder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[API.models.validate_unique_phone]),
        ),
    ]
