# Generated by Django 5.1.6 on 2025-03-23 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_book_user_cart_user_contact_user_miscellaneous_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Miscellaneous',
        ),
    ]
